a3_group16/BeatBazaar/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from .forms import LoginForm,RegisterForm
# new imports:
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import generate_password_hash, check_password_hash
from . import db

# Create a blueprint - make sure all BPs have unique names
auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form is fine, HTTP request is POST
    if (register.validate_on_submit()==True):
            #get username, password and email from the form
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            #check if a user exists
            user = db.session.scalar(db.select(User).where(User.name==uname))
            if user:#this returns true when user is not None
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            # don't store the password in plaintext!
            pwd_hash = generate_password_hash(pwd).decode('utf-8')
            #create a new User model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when the HTTP request calling this page is a GET
    else:
        return render_template('login.html', form=register, heading='Register')
    

# this is the hint for a login function
@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = User.query.filter_by(name=user_name).first()
        #if there is no user with that name
        if user is None:
            error = 'Invalid User'
        elif  check_password_hash(user.password_hash, password):
            error = 'Invalid Password'
            #error message does not specifcally say which is wrong
        elif error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(user)
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('login.html', form=login_form, heading='Login')


@auth_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

a3_group16/BeatBazaar/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required
from .models import Event, Bookings
from . import db

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    events = db.session.scalars(db.select(Event)).all()
    return render_template('index.html', events=events)

@main_bp.route('/filter/<country>')
def filter(country):
        events = db.session.scalars(db.select(Event).where(Event.country.like(country)))
        return render_template('index.html', events=events)

@main_bp.route('/history/<id>')
@login_required
def history(id):

    bookings = Bookings.query.join(Event, Bookings.events_id==Event.id).filter(Bookings.user_id==id)
    return render_template('booking-history.html', bookings=bookings)

a3_group16/BeatBazaar/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{{url_for('static', filename='style/style.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BeatBazaar - Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
        <!-- Header -->
        <header>
            <!-- Navigation Bar -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
                <div class="container-fluid">
                    <a href="{{ url_for('main.index') }}"><img id="logo" src="/static/img/logo-removebg.png" height="70" alt="logo"></a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{{ url_for('main.index') }}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('event.create_event') }}">Create Event</a>
                            </li>
                            {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.history', id=current_user.id) }}">Booking History</a>
                            </li>
                            {% endif %}
                            &nbsp;
                            <li class="nav-item">
                                <!-- <a class="nav-link" id="register-login-button"
                                    href="{{ url_for('auth.login') }}">&nbsp;Register/Login&nbsp;</a> -->
                                {% if current_user.is_authenticated %}
                                <li>
                                    <a class="nav-item nav-link disabled text-muted" href="#">Welcome {{current_user.name}}</a>
                                </li>
                                <li>
                                    <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                                </li>
                                {% else %}
                                <li>
                                    <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                                </li>
                                <li>
                                    <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                                </li>
                                {% endif %}
                            </li>

                        </ul>
                        <form class="d-flex">
                            <input id=navSearch class="form-control me-2" type="search"
                                placeholder="Search by Artist, Country..." aria-label="Search">
                            <button class="btn btn-outline-success" type="submit" id="searchbtn">Search</button>
                            <a href="{{ url_for('main.index') }}"><img id="shopping-bag"
                                    src="/static/img/shopping-bag-bg.png" height="35" alt="shopping bag"></a>
                        </form>
                    </div>
                </div>
            </nav>
            <!-- Code for using Flask flash -->
            <div class="container-fluid">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                {% for message in get_flashed_messages() %}
                <div class="alert alert-warning" id="flash">
                    <div id="flashalert">
                        {{message}} 
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>

            {% block header %}

            {% endblock %}

        </header>

        {% block content %}

        {% endblock %}

        <footer>
            <div class="footerLinks text-center col-12" id="footer">
                <div class=" text-center">
                    <ul class="list-unstyled" id="footerNav">
                        <br>
                        <li id="bottomNav">
                            <a href="{{ url_for('main.index') }}" class="text-dark">Home</a>
                        </li>
                        <li id="bottomNav">
                            <a href="{{ url_for('event.create_event') }}" class="text-dark">Create Event</a>
                        </li>
                        <li id="bottomNav">
                            <a href="{{ url_for('main.history', id=current_user.id) }}" class="text-dark">Booking History</a>
                        </li>
                    </ul>
                    </class>
                </div>
                <div>
                    <a href=#><img id="logo" src="/static/img/logo-removebg.png" height="100" alt="logo"></a>
                    <a href=#><img id="payment methods" src="/static/img/payment-bg.png" height="40"
                            alt="payment methods"></a>
                </div>
                <div class="p-3" id="footer">
                    Copyright &copy 2023 //
                    <br />
                    BeatBazaar recognises and pays respect to the Traditional Custodians - the Jagera and Turrbal - on the
                    land on which we enjoy our music.
                </div>
            </div>
        </footer>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</html>

a3_group16/BeatBazaar/templates/booking-history.html
{% extends "base.html" %}

{% block content %}
<br />
<h1 style="text-align: center;"> Booking History</h1>

<table class="table" id="bookingHistory">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col"> </th>
            <th scope="col">Event</th>
            <th scope="col">Booking ID</th>
            <th scope="col">Time/Date of booking</th>
        </tr>
    </thead>
    {%for booking in bookings%}
    <tbody>
        <tr class="booking">
            <th scope="col" id="bookingNo">{{booking.id}}</th>

            <td><img src="" alt="Arijit Singh" class="img-thumbnail"></td>
            <td>Arijit Singh (April 14, 2023)
                <p><a href="{{ url_for('event.show', id=booking.id) }}" class="btn btn-light">View Details</a></p>
            </td>
            <td>{{booking.booking_number}}</td>
            <td>{{booking.created_at}}</td>
        </tr>

    </tbody>
    {%endfor%}
</table>

<!--Button group-->
<div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group me-2" role="group" aria-label="First group">
        <button type="button" class="btn btn-secondary">1</button>
        <button type="button" class="btn btn-outline-secondary">2</button>
        <button type="button" class="btn btn-outline-secondary">3</button>
        <button type="button" class="btn btn-outline-secondary">4</button>
    </div>
    <div class="input-group">
        <div class="input-group-text" id="btnGroupAddon">🔍</div>
        <input type="text" class="form-control" placeholder="Search a booking" aria-label="Input group example"
            aria-describedby="btnGroupAddon">
    </div>
</div>
{% endblock %}

a3_group16/BeatBazaar/templates/event-details.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="static/style/css.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shae Gill: Full Circle Tour</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <header>
       <!-- Navigation Bar -->
       <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a href="index.html"><img id="logo" src="static/img/logo-removebg.png" height="70" alt="logo"></a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="index.html">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="event-creation-update.html">Create/Update Event</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="booking-history.html">Booking History</a>
                    </li>
                    &nbsp;
                    <li class="nav-item">
                        <a class="nav-link" id="register-login-button" href="#">&nbsp;Welcome, Supriya&nbsp;</a>
                    </li>

                </ul>
                <form class="d-flex">
                    <input id=navSearch class="form-control me-2" type="search" placeholder="Search by Artist, Country..." aria-label="Search">
                    <button class="btn btn-outline-success" type="submit" id="searchbtn">Search</button>
                    <a href="index.html"><img id="shopping-bag" src="static/img/shopping-bag-bg.png" height="35" alt="shopping bag"></a>
                </form>
            </div>
        </div>
    </nav>

        <div class="mainEvent">
            <div class="container text-center col-sm-6"></div>
            <img src="static/img/shae-gill3.png" class="img-fluid" id="eventPhoto" alt="Shae Gill">
            </div>
        </div>
    </header>


    <div class="container text-center">

        <div class="row">
            <div>
                <h1 class="col-md"> <span id="chosenEventTitle">Shae Gill: Full Circle Tour</span></h1>
                <h2 style="background-color: rgba(144, 238, 144, 0.2); color: darkcyan;"><img id="logo" src="static/img/pakistan.png" width="50" height="50" alt="Pakistan flag"> Pakistan</h2>
            </div>
        </div> <!--end of row-->
        <div class="row">
            <div class="col-12 col-md-7">
                <div>
                    <h3 id="cardEventDate"> Wednesday, September 27 2023, 7:00 PM - 11:00 PM</h3>
                    <h4 id="cardLocation"> Riverstage • 59 Gardens Point Rd, Brisbane City • QLD 4000</h4>
                </div>
                <div>
                    <button type="button" class="btn btn-primary col-md" id="bookTicketsModal2" data-bs-toggle="modal"
                        data-bs-target="#exampleModal" style="font-size: larger;">
                        BOOK NOW!
                        Event is <u>Open</u>
                    </button>
                </div>
            </div>
            <div class="col-12 col-md-5">
                <div>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14158.727884959204!2d153.0300464!3d-27.4791587!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b915a110598d1af%3A0xa18cc7aeb141039b!2sRiverstage!5e0!3m2!1sen!2sau!4v1694738364365!5m2!1sen!2sau" width="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div> <!--end of row-->
        <br/>

        <!--Event description onwards-->
            <p class="card-text">🌟 Experience the Magic of Shae Gill Live in Concert! 🌟
                Prepare to be swept off your feet and immersed in a musical journey like no other as Shae Gill, the sensational artist of Pasoori fame, takes centre stage for a concert that promises to be nothing short of extraordinary.
                🎶 The Soundtrack to Your Soul 🎶</p>

            <div class="ticket-modal">
                <!-- Modal window itself -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Book Tickets</h5>
                                <button type="button" class="btn-close" id="bookTicketsModal" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-sm-12" id="modal-eventName">
                                        <span id="chosenEventTitle"><b>Shae Gill: Full Circle Tour</b></span>
                                        <h3 id="cardEventDate" style="font-size: medium;"> Wed, Sept 27 2023, 7:00 PM</h3>
                                        <h4 id="cardLocation" style="font-size: small;"> Riverstage • 59 Gardens Point Rd, Brisbane City • QLD 4000 </h4>
                                        <div class="row">
                                            <div class="col-6 col-sm-6">
                                                <div class="form-floating mb-3">
                                                    <input type="name" class="form-control" id="floatingInput"
                                                        placeholder="Festival">
                                                    <label for="floatingInput">Promo Code</label>
                                                </div>
                                                <div class="col-6 col-sm-6">
                                                    <h6 id="refundtxt">
                                                        <b id="refundpolicy">Refund Policy:</b> Contact the organiser to
                                                        request a refund.
                                                        The booking fee is non-refundable.
                                                        <br>
                                                        </6>
                                                </div>
                                            </div>
                                            <div class="col-6 col-sm-6">
                                                <img class="img-thumbnail" src="static/img/shae-gill3.png">
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <label for="floatingInput" id="modal-eventTicket">Tickets</label>
                                <div class="form-outline">
                                    <label class="form-label" for="typeNumber">VIP $120</label>
                                    <input value="0" min="0" max="100" type="number" id="typeNumber"
                                        class="form-control" />
                                </div>
                                <div class="form-outline">
                                    <label class=" form-label" for="typeNumber">General $90</label>
                                    <input value="0" min="0" max="100" type="number" id="typeNumber"
                                        class="form-control" />
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" id="bookTicketsModal"
                                    data-bs-dismiss="modal">Cancel</button>
                                <button type="button" class="btn btn-primary" id="bookTicketsModal">Book
                                    tickets</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <h3 id="Upcoming">User Comments</h3>
            <div class="row">
                <div class="col-lg-3 col-sm-12 col-md-4">
                    <div class="usercommentscontainer">
                        <p>Make sure you go early to avoid parking issues!</p>
                        <img id="comment" src="static/img/user.jpg" alt="Avatar">
                        <p><span>Imaan E Telat</span> • Sep 15th 2023, 4:04PM</p>
                    </div>
                </div>

                <div class="col-lg-3 col-sm-12 col-md-4">
                    <div class="usercommentscontainer">
                        <p>Loved this event last year. Will definitely be going.</p>
                        <img id="comment" src="static/img/user.jpg" alt="Avatar">
                        <p><span>Talia</span> • Sep 3rd 2023, 8:43AM</p>
                    </div>
                </div>


                <div class="col-lg-3 col-sm-12 col-md-4">
                    <div class="usercommentscontainer">
                        <p>I've been waiting all year!</p>
                        <img id="comment" src="static/img/user.jpg" alt="Avatar">
                        <p><span>Al O'Mally</span> • Aug 29th 2023, 6:56AM</p>
                    </div>
                </div>


                <div class="col-lg-3 col-sm-12 col-md-4">
                    <div class="usercommentscontainer">
                        <p>Forever a Pasoori fan!</p>
                        <img id="comment" src="static/img/user.jpg" alt="Avatar">
                        <p><span></span> Ali Sethi • Aug 17th 2023, 10:13PM</p>
                    </div>
                </div>

                <div class="comments">
                    <form class="form-floating">
                        <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2"
                            style="height: 100px" required></textarea>
                        <label for="floatingTextarea2">Write Comment...</label>
                        <input type="submit" class="btn btn-primary" id="bookTicketsModal">
                    </form>
                </div>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
            </div>
        </div>
    </div>
    </body>

<footer>
    <div class="footerLinks text-center col-12" id="footer">
        <div class="text-center">
            <ul class="list-unstyled" id="footerNav">
                <br>
                <li id="bottomNav">
                    <a href="index.html" class="text-dark">Home</a>
                </li>
                <li id="bottomNav">
                    <a href="event-creation-update.html" class="text-dark">Create/Update Event</a>
                </li>
                <li id="bottomNav">
                    <a href="booking-history.html" class="text-dark">Booking History</a>
                </li>
            </ul>
            </class>
        </div>
    <div>
        <a href="index.html"><img id="logo" src="static/img/logo-removebg.png" height="100" alt="logo"></a>
        <a href="index.html"><img id="payment methods" src="static/img/payment-bg.png" height="40" alt="payment methods"></a>
    </div>
        <div class="p-3" id="footer">
            Copyright &copy 2023 Arushi Bose // 
            <br/>
            BeatBazaar recognises and pays respect to the Traditional Custodians - the Jagera and Turrbal - on the land on which we enjoy our music.
        </div>
    </div>
</footer>

</html>
    

a3_group16/BeatBazaar/templates/index.html
{% extends "base.html" %}

{% block header %}
<!--Jumbotron-->
<div class="jumbotronback p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5 rounded-3" id="homeJumbotron">
        <h1 class="display-5 fw-bold" id="slogan"> Your Musical Market </h1>
        <p class="col-md-8 fs-4" id="slogan"> One beat at a time. Step into a vibrant musical marketplace where
            boundaries blur, and rhythms collide. BeatBazaar is your passport to concerts by rising international
            artists, bringing together diverse cultures and genres to create a symphony of unforgettable moments.
        </p>

        <a href="{{ url_for('event.show', id=0) }}" class="btn btn-primary btn-lg" id="btnSurprise" type="button">View Our
            Featured
            Event</a>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container text-center">
    <h2 id="home-title" style="color: #780087;">🎶🎵 𝓜𝓾𝓼𝓲𝓬 𝓕𝓮𝓼𝓽𝓲𝓿𝓪𝓵𝓼 🎵🎶</h2>

    <h3 id="Upcoming">Browse by Category (Country of Origin)</h3>

    <!-- Control buttons -->
    <div id="myBtnContainer">
        <a class="btn festivalCategory" href="{{ url_for('main.filter', country='Pakistan')}}">Pakistan</a>
        <a class="btn festivalCategory" href="{{ url_for('main.filter', country='Japan')}}">Japan</a>
        <a class="btn festivalCategory" href="{{ url_for('main.index')}}">Show All</a>
    </div>

    <!--UPCOMING FESTIVALS-->
    <h3 id="Upcoming">Upcoming Festivals</h3>
    <div class="Categorycontainer">
        <div class="row">
            {% for event in events %}
            <div class="col-lg-3 col-sm-12 col-md-4">
                <div class="card">
                    <img class="card-img-top" src="{{event.image}}" alt="Card image">
                    <span class="flag"><img title="Pakistan" id="logo" src="static/img/{{event.country}}.png" width="40"
                            alt="Pakistan flag"></span>
                    <span class="badge badge-secondary" id="inactive"> {{event.status}} </span>
                    <div class="card-body">
                        <h5 class="card-title">{{ event.name }}</h5>
                        <h3 id="cardEventDate"> {{ event.date }}, {{ event.start_time }}</h3>
                        <h4 id="cardLocation"> {{event.venue}} • {{event.city}} • {{event.state}}</h4>

                        <p class="card-text">
                            Prepare to be swept off your feet and immersed in a musical journey like no other.
                        </p>
                        <a href="{{ url_for('event.show', id=event.id) }}" class="btn btn-primary" id="btnEventDetails"> Details
                            🠲
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div> <!--end of category-->
</div>

{% endblock %}

a3_group16/BeatBazaar/templates/login.html
{% extends "base.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container-fluid" id="loginpage">
<div class="page-header">
    <h4>{{ heading }}</h4>
</div>

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6 ml-5" id="Register">
    <div>
        {{ render_form(form) }}
    </div>
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower == 'login' %}
<div class="col-md-4 mb-5 ml-5">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}
</div>
{% endblock %}

a3_group16/BeatBazaar/templates/user.html
{% include "base.html" %}
{% from "bootstrap5/form.html" import render_form %}
{% block body %}

<div class="page-header">
    <h4>{{heading}}</h4>
</div>

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6">
    {{render_form(form)}}
</div>

<!-- When you have login form, then show the user a link to register to the website -->
{% if heading|lower =='login' %}
<div class="col-md-4">
    <p>New user? <a href="{{ url_for('register') }}">Click Here to Register!</a>.</p>
</div>
{% endif %}

{% endblock %}